# pytest.ini
[pytest]
addopts = -v --strict-markers --tb=short --color=yes
markers =
    smoke: Smoke tests
    regression: Regression tests
    main_functionality: Main functionality tests
    order_feed: Order feed tests
    slow: Slow tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore:.*